"""PDF report generation — risk snapshot for the portfolio demo."""

from __future__ import annotations

import io
from datetime import UTC, datetime
from decimal import Decimal
from typing import Annotated

from fastapi import APIRouter, Depends, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.core.security import UserPrincipal, get_current_user

router = APIRouter(prefix="/reports", tags=["reports"])


class RiskPdfRequest(BaseModel):
    portfolio_value_brl: Decimal | None = None
    var_flat_brl: Decimal | None = None
    var_per_leg: dict[str, Decimal] = Field(default_factory=dict)
    cvar_flat_brl: Decimal | None = None
    stress_results: list[dict[str, str]] = Field(default_factory=list)
    attribution_top: list[dict[str, str]] = Field(default_factory=list)
    confidence: Decimal = Decimal("0.95")
    horizon_days: int = 1


def _build_pdf(body: RiskPdfRequest, user_email: str) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=1.5 * cm,
        leftMargin=1.5 * cm,
        topMargin=1.5 * cm,
        bottomMargin=1.5 * cm,
    )
    styles = getSampleStyleSheet()
    elements = []

    now = datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M UTC")
    elements.append(Paragraph("Market Risk Snapshot", styles["Title"]))
    elements.append(Paragraph(f"Generated {now} for {user_email}", styles["Normal"]))
    elements.append(Spacer(1, 0.5 * cm))

    # Parameters
    param_data = [
        ["Confidence", f"{body.confidence:.4f}"],
        ["Horizon (days)", str(body.horizon_days)],
        [
            "Portfolio value (BRL)",
            f"{body.portfolio_value_brl:,.2f}" if body.portfolio_value_brl is not None else "—",
        ],
    ]
    elements.append(_table("Parameters", param_data))
    elements.append(Spacer(1, 0.3 * cm))

    # VaR / CVaR
    var_rows: list[list[str]] = [
        ["Flat VaR (BRL)", f"{body.var_flat_brl:,.2f}" if body.var_flat_brl is not None else "—"],
        ["CVaR (BRL)", f"{body.cvar_flat_brl:,.2f}" if body.cvar_flat_brl is not None else "—"],
    ]
    for leg, value in sorted(body.var_per_leg.items()):
        var_rows.append([f"VaR {leg}", f"{value:,.2f}"])
    elements.append(_table("VaR / CVaR", var_rows))
    elements.append(Spacer(1, 0.3 * cm))

    # Stress
    if body.stress_results:
        stress_rows = [["Scenario", "Total P&L (BRL)"]]
        stress_rows.extend(
            [row.get("scenario_name", "?"), row.get("total_pnl_brl", "?")]
            for row in body.stress_results
        )
        elements.append(_table("Stress results", stress_rows, has_header=True))
        elements.append(Spacer(1, 0.3 * cm))

    # Attribution
    if body.attribution_top:
        attr_rows = [["Label", "Contribution (BRL)", "Share (%)"]]
        attr_rows.extend(
            [
                row.get("label", "?"),
                row.get("contribution_brl", "?"),
                row.get("share_pct", "?"),
            ]
            for row in body.attribution_top[:10]
        )
        elements.append(_table("Attribution — top 10", attr_rows, has_header=True))

    elements.append(Spacer(1, 1 * cm))
    elements.append(
        Paragraph(
            "Generated by the market-risk-platform (Phase 11 PDF export).",
            styles["Italic"],
        ),
    )

    doc.build(elements)
    return buffer.getvalue()


def _table(title: str, data: list[list[str]], has_header: bool = False) -> Table:
    style_commands: list[tuple[object, ...]] = [
        ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]
    if has_header:
        style_commands.append(("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey))
        style_commands.append(("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"))
        header_row = [[f"{title}"]]
        header_style = TableStyle(
            [("FONTSIZE", (0, 0), (0, 0), 11), ("FONTNAME", (0, 0), (0, 0), "Helvetica-Bold")]
        )
        body_table = Table([*data], colWidths=[6 * cm] * len(data[0]))
        body_table.setStyle(TableStyle(style_commands))
        title_table = Table(header_row)
        title_table.setStyle(header_style)
        return Table([[title_table], [body_table]], colWidths=[18 * cm])
    body = Table([[title], *data], colWidths=[6 * cm, 12 * cm])
    body.setStyle(
        TableStyle(
            [
                *style_commands,
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("SPAN", (0, 0), (-1, 0)),
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("ALIGN", (0, 0), (-1, 0), "LEFT"),
            ],
        )
    )
    return body


@router.post(
    "/risk-pdf",
    status_code=status.HTTP_200_OK,
    responses={200: {"content": {"application/pdf": {}}}},
)
async def risk_pdf(
    body: RiskPdfRequest,
    principal: Annotated[UserPrincipal, Depends(get_current_user)],
) -> StreamingResponse:
    pdf_bytes = _build_pdf(body, user_email=principal.email)
    filename = f"risk-report-{datetime.now(tz=UTC).strftime('%Y%m%d-%H%M%S')}.pdf"
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
